api:
  host: 0.0.0.0
  port: 5000
  auth:
    enabled: false
    key: abcd1234
  https:
    enabled: true
    private_key: pz.key
    public_key: pz.crt
  accesslog: true
  logping: true

daemons:
  - name: test stdout
    description: simple test for stdout logging
    command: /bin/sh
    args:
      - -c
      - "while true; do echo 'stdout'; sleep 1; done"
    vital: true
    log: true
    env:

  - name: test stderr
    description: simple test for stderr logging
    command: /bin/sh
    args: 
      - -c
      - "while true; do echo 'error' 1>&2; sleep 1; done"
    vital: true
    log: true
    env:

pidzero:
  buffersize: 4096
  loglevel: debug
  prettylogging: true
